"""Undisputed Pydantic schemas for boxing AI agents."""

from app.schemas.undisputed.boxing import (
    ArchetypeClassification,
    BodyWorkROI,
    BoxingArchetype,
    CareerBuildPath,
    ComboAnalysis,
    CutOffAngle,
    DamageState,
    DamageTimeline,
    FightGameplan,
    GuardBreakReport,
    JabEconomyReport,
    PunchEconomyReport,
    PunchPackage,
    RingPositionAnalysis,
    RopeTracker,
    RoundBankStrategy,
    RoundScore,
    ScorecardProjection,
    StanceMatchup,
    TrainingCampPlan,
)

__all__ = [
    "ArchetypeClassification",
    "BodyWorkROI",
    "BoxingArchetype",
    "CareerBuildPath",
    "ComboAnalysis",
    "CutOffAngle",
    "DamageState",
    "DamageTimeline",
    "FightGameplan",
    "GuardBreakReport",
    "JabEconomyReport",
    "PunchEconomyReport",
    "PunchPackage",
    "RingPositionAnalysis",
    "RopeTracker",
    "RoundBankStrategy",
    "RoundScore",
    "ScorecardProjection",
    "StanceMatchup",
    "TrainingCampPlan",
]
