"""Defensive strategy models.

Companion to ``app.models.secret_weapon`` — these models persist defensive
gameplans (per-opponent scheme + adjustments) and the player's defensive
priority weaknesses surfaced by ImpactRank.

Schema is intentionally lean: heavy structured payloads (situational
packages, opponent counters, etc.) live in JSON columns rather than
normalised side tables. The vast majority of reads are 'load by user_id'
and the payload is rendered as-is.
"""

from __future__ import annotations

from typing import Any

from sqlalchemy import (
    JSON,
    Float,
    ForeignKey,
    Integer,
    String,
)
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base
from app.models.base import UUIDPrimaryKeyMixin


class DefensiveGameplan(UUIDPrimaryKeyMixin, Base):
    """A complete defensive gameplan generated by DefenseAI for a matchup."""

    __tablename__ = "defensive_gameplans"

    user_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    title_id: Mapped[str] = mapped_column(String(32), nullable=False, index=True)
    opponent_id: Mapped[str | None] = mapped_column(String(64), nullable=True)
    scheme: Mapped[str] = mapped_column(String(120), nullable=False)
    concepts: Mapped[list[Any]] = mapped_column(JSON, default=list, nullable=False)
    adjustments: Mapped[list[Any]] = mapped_column(JSON, default=list, nullable=False)
    # Full DefenseAI payload — situational packages, opponent counters, etc.
    payload: Mapped[dict[str, Any]] = mapped_column(JSON, default=dict, nullable=False)
    meta_version: Mapped[str | None] = mapped_column(String(32), nullable=True)


class DefensivePriority(UUIDPrimaryKeyMixin, Base):
    """A ranked defensive weakness for a player on a title.

    Mirrors the offensive priority model used by ImpactRank — each row is
    one weakness with its win-rate damage and expected lift if fixed.
    """

    __tablename__ = "defensive_priorities"

    user_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    title_id: Mapped[str] = mapped_column(String(32), nullable=False, index=True)
    rank: Mapped[int] = mapped_column(Integer, nullable=False)
    name: Mapped[str] = mapped_column(String(160), nullable=False)
    category: Mapped[str] = mapped_column(String(64), nullable=False)
    win_rate_damage: Mapped[float] = mapped_column(Float, default=0.0, nullable=False)
    expected_lift: Mapped[float] = mapped_column(Float, default=0.0, nullable=False)
    impact_score: Mapped[float] = mapped_column(Float, default=0.0, nullable=False)
    confidence: Mapped[float] = mapped_column(Float, default=0.0, nullable=False)
