export type SituationTag =
  | 'red-zone'
  | 'goal-line'
  | '3rd-down'
  | '2-minute'
  | 'opening-drive'
  | 'anti-blitz'
  | 'prevent'
  | 'hurry-up';

export type Formation =
  | 'Gun Spread'
  | 'Gun Trips TE'
  | 'Singleback Ace'
  | 'Shotgun Trips'
  | 'Shotgun Bunch'
  | 'I-Form Close'
  | 'Gun Empty'
  | 'Pistol Strong'
  | 'Singleback Deuce Close'
  | 'Gun Trey Open'
  | 'Nickel Double A Gap'
  | '3-4 Odd'
  | '4-3 Under'
  | 'Dime Normal';

export type ConceptTag =
  | 'man-beater'
  | 'zone-beater'
  | 'screen'
  | 'rpo'
  | 'play-action'
  | 'quick-pass'
  | 'deep-shot'
  | 'run'
  | 'draw'
  | 'misdirection';

export interface PlayEvidence {
  why: string;
  data: string;
  risk: string;
  comparable: string;
}

export interface PlayCallStructureLayer1 {
  name: string;
  description: string;
}
export interface PlayCallStructureLayer2 {
  audible: string;
  trigger: string;
  description: string;
}
export interface PlayCallStructure {
  layer1: PlayCallStructureLayer1;
  layer2: PlayCallStructureLayer2[];
  layer3: string;
}

export interface Play {
  id: string;
  name: string;
  formation: string; // free-text — title-specific, no longer constrained
  conceptTags: string[]; // free-text tags
  situationTags: SituationTag[];
  confidenceScore: number; // 0-100
  isKillSheetPlay: boolean;
  description: string;
  beats?: string;
  audibleOptions?: AudibleNode[];

  // GameplanAI fields (populated when generated by Claude / mock)
  rank?: number;
  tags?: string[];
  impactScore?: number;
  masteryLevel?: 'Competition Ready' | 'Practicing' | 'Learning' | string;
  executionRate?: number; // 0-100
  isTrendingCountered?: boolean;
  whenToCall?: string;
  conceptBreakdown?: string;
  evidence?: PlayEvidence;
  proofAIConfidence?: number;
  callStructure?: PlayCallStructure;
  metaStatus?: 'Strong' | 'Stable' | 'Countered' | 'Exploit' | string;
  patchVersion?: string;
}

export interface AudibleNode {
  id: string;
  label: string;
  trigger: string; // e.g., "Cover 3 detected", "Blitz look"
  targetPlay: string;
  children?: AudibleNode[];
}

export type MetaRating = 'Exploit' | 'Strong' | 'Neutral' | 'Countered';

export interface MetaStatus {
  rating: MetaRating;
  patchVersion: string;
  lastUpdated: string;
}

export interface PackageHealth {
  complete: boolean;
  plays: string[];
  missing?: string | null;
  healthMessage?: string;
}

export interface ScriptViewEntry {
  order: number;
  playName: string;
  formation: string;
  callWhen: string;
  confidence: number;
  impactScore: number;
  masteryLevel: string;
}

export interface KillSheetEntry {
  rank: number;
  name: string;
  formation: string;
  confidence: number;
  whenToCall: string;
}

export interface TwoMinDrillEntry {
  time: string;
  situation: string;
  call: string;
}

export interface OpponentSummary {
  topCoverage?: string;
  topCoveragePercent?: number;
  blitzRate?: number;
  tendency3?: string;
  tendency3Percent?: number;
  defensiveSchemer?: string;
  winRate?: number;
}

export interface Gameplan {
  id: string;
  name: string;
  opponentId: string;
  opponentName: string;
  plays: Play[];
  killSheet: Play[];
  redZonePackage: Play[];
  antiBlitzPackage: Play[];
  twoMinDrillPackage: Play[];
  metaStatus: MetaStatus;
  createdAt: string;
  updatedAt: string;

  // Generated additions
  generatedId?: string; // backend Gameplan row id
  source?: 'claude' | 'mock' | 'cache';
  cached?: boolean;
  killSheetStructured?: KillSheetEntry[];
  scriptView?: ScriptViewEntry[];
  antiBlitzPackageHealth?: PackageHealth;
  redZonePackageHealth?: PackageHealth;
  twoMinDrill?: TwoMinDrillEntry[];
  opponentSummary?: OpponentSummary;
  metaVersion?: string;
  overallStrategy?: string;
  patchVersion?: string;
}

export type PackageTab = 'all' | 'kill-sheet' | 'red-zone' | 'anti-blitz' | '2-min-drill';
