"""clean baseline (32 tables incl folded-in live endpoints)

Revision ID: ffa2cd90434a
Revises: 
Create Date: 2026-07-05 13:53:42.478156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffa2cd90434a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_performances',
    sa.Column('agent_name', sa.String(length=100), nullable=False, comment='Agent identifier'),
    sa.Column('title', sa.String(length=100), nullable=False, comment='Game title scope'),
    sa.Column('total_recommendations', sa.Integer(), nullable=False),
    sa.Column('correct_predictions', sa.Integer(), nullable=False),
    sa.Column('accuracy_rate', sa.Float(), nullable=False, comment='correct / total ratio'),
    sa.Column('last_audit_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_performances_agent_name'), 'agent_performances', ['agent_name'], unique=False)
    op.create_table('animaforge_jobs',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('title_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('spec', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_animaforge_jobs_job_id'), 'animaforge_jobs', ['job_id'], unique=True)
    op.create_index(op.f('ix_animaforge_jobs_source_id'), 'animaforge_jobs', ['source_id'], unique=False)
    op.create_index(op.f('ix_animaforge_jobs_status'), 'animaforge_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_animaforge_jobs_title_id'), 'animaforge_jobs', ['title_id'], unique=False)
    op.create_index(op.f('ix_animaforge_jobs_type'), 'animaforge_jobs', ['type'], unique=False)
    op.create_index(op.f('ix_animaforge_jobs_user_id'), 'animaforge_jobs', ['user_id'], unique=False)
    op.create_table('cfb_schemes',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('OFFENSE', 'DEFENSE', name='cfb_scheme_type', native_enum=False), nullable=False),
    sa.Column('concepts', sa.JSON(), nullable=True, comment='Core scheme concepts'),
    sa.Column('coverage_matrix', sa.JSON(), nullable=True, comment='Coverage matchup matrix'),
    sa.Column('momentum_impact', sa.JSON(), nullable=True, comment='How momentum affects scheme effectiveness'),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cfb_schemes_name'), 'cfb_schemes', ['name'], unique=False)
    op.create_table('madden_schemes',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('OFFENSE', 'DEFENSE', name='scheme_type', native_enum=False), nullable=False),
    sa.Column('concepts', sa.JSON(), nullable=True, comment='Core scheme concepts and principles'),
    sa.Column('coverage_matrix', sa.JSON(), nullable=True, comment='Coverage matchup matrix'),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_madden_schemes_name'), 'madden_schemes', ['name'], unique=False)
    op.create_table('opponents',
    sa.Column('external_id', sa.String(length=255), nullable=True, comment='Platform-specific player ID'),
    sa.Column('gamertag', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False, comment='Game title'),
    sa.Column('archetype', sa.String(length=100), nullable=True, comment='Classified playstyle archetype'),
    sa.Column('tendencies', sa.JSON(), nullable=True, comment='Observed behavioral tendencies'),
    sa.Column('encounter_count', sa.Integer(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opponents_external_id'), 'opponents', ['external_id'], unique=True)
    op.create_index(op.f('ix_opponents_gamertag'), 'opponents', ['gamertag'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.Enum('FREE', 'COMPETITIVE', 'ELITE', 'TEAM', name='user_role', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('active_title', sa.String(length=100), nullable=True, comment='Currently active game title'),
    sa.Column('two_factor_enabled', sa.Boolean(), nullable=False),
    sa.Column('two_factor_secret', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('api_usage',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('agent', sa.String(length=50), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('title_id', sa.String(length=50), nullable=False),
    sa.Column('cached', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('certifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title_id', sa.String(length=50), nullable=False),
    sa.Column('skill_dimension', sa.String(length=100), nullable=False),
    sa.Column('percentile', sa.Integer(), nullable=False),
    sa.Column('awarded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cfb_plays',
    sa.Column('scheme_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('formation', sa.String(length=100), nullable=False),
    sa.Column('play_type', sa.String(length=50), nullable=False),
    sa.Column('success_rate', sa.Float(), nullable=False),
    sa.Column('situation_tags', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['scheme_id'], ['cfb_schemes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cfb_plays_formation'), 'cfb_plays', ['formation'], unique=False)
    op.create_index(op.f('ix_cfb_plays_scheme_id'), 'cfb_plays', ['scheme_id'], unique=False)
    op.create_table('cfb_recruiting_targets',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('position', sa.String(length=10), nullable=False),
    sa.Column('star_rating', sa.Integer(), nullable=False),
    sa.Column('overall_rating', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('high_school', sa.String(length=200), nullable=True),
    sa.Column('interest_level', sa.Float(), nullable=False, comment='0.0-1.0 interest in your program'),
    sa.Column('pipeline_stage', sa.Enum('SCOUTED', 'CONTACTED', 'VISITED', 'COMMITTED', 'SIGNED', name='recruiting_pipeline', native_enum=False), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=True, comment='Detailed recruit attributes'),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cfb_recruiting_targets_pipeline_stage'), 'cfb_recruiting_targets', ['pipeline_stage'], unique=False)
    op.create_index(op.f('ix_cfb_recruiting_targets_position'), 'cfb_recruiting_targets', ['position'], unique=False)
    op.create_index(op.f('ix_cfb_recruiting_targets_user_id'), 'cfb_recruiting_targets', ['user_id'], unique=False)
    op.create_table('daily_forge_completions',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('drill_done', sa.Boolean(), nullable=False),
    sa.Column('focus_done', sa.Boolean(), nullable=False),
    sa.Column('mental_done', sa.Boolean(), nullable=False),
    sa.Column('meta_done', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_daily_forge_completions_user_date')
    )
    op.create_index(op.f('ix_daily_forge_completions_date'), 'daily_forge_completions', ['date'], unique=False)
    op.create_index(op.f('ix_daily_forge_completions_user_id'), 'daily_forge_completions', ['user_id'], unique=False)
    op.create_table('daily_forge_streaks',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('last_completed_date', sa.Date(), nullable=True),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_forge_streaks_user_id'), 'daily_forge_streaks', ['user_id'], unique=True)
    op.create_table('defensive_gameplans',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title_id', sa.String(length=32), nullable=False),
    sa.Column('opponent_id', sa.String(length=64), nullable=True),
    sa.Column('scheme', sa.String(length=120), nullable=False),
    sa.Column('concepts', sa.JSON(), nullable=False),
    sa.Column('adjustments', sa.JSON(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('meta_version', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_defensive_gameplans_title_id'), 'defensive_gameplans', ['title_id'], unique=False)
    op.create_index(op.f('ix_defensive_gameplans_user_id'), 'defensive_gameplans', ['user_id'], unique=False)
    op.create_table('defensive_priorities',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title_id', sa.String(length=32), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('win_rate_damage', sa.Float(), nullable=False),
    sa.Column('expected_lift', sa.Float(), nullable=False),
    sa.Column('impact_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_defensive_priorities_title_id'), 'defensive_priorities', ['title_id'], unique=False)
    op.create_index(op.f('ix_defensive_priorities_user_id'), 'defensive_priorities', ['user_id'], unique=False)
    op.create_table('drills',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False, comment='Game title'),
    sa.Column('skill_target', sa.String(length=200), nullable=False, comment='Skill being trained'),
    sa.Column('difficulty_level', sa.String(length=50), nullable=False, comment='e.g. beginner, intermediate, advanced'),
    sa.Column('drill_config', sa.JSON(), nullable=True, comment='Configuration parameters for the drill'),
    sa.Column('completion_count', sa.Integer(), nullable=False),
    sa.Column('success_rate', sa.Float(), nullable=False, comment='Ratio of successful completions'),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drills_user_id'), 'drills', ['user_id'], unique=False)
    op.create_table('game_sessions',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False, comment='Game title'),
    sa.Column('mode', sa.Enum('RANKED', 'TOURNAMENT', 'TRAINING', name='game_mode', native_enum=False), nullable=False),
    sa.Column('opponent_id', sa.String(length=36), nullable=True),
    sa.Column('result', sa.Enum('WIN', 'LOSS', 'DRAW', name='game_result', native_enum=False), nullable=False),
    sa.Column('stats', sa.JSON(), nullable=True, comment='Raw game stats blob'),
    sa.Column('recommendations_followed', sa.JSON(), nullable=True, comment='Which recommendations were applied'),
    sa.Column('session_duration', sa.Integer(), nullable=True, comment='Duration in seconds'),
    sa.Column('played_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['opponent_id'], ['opponents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_sessions_opponent_id'), 'game_sessions', ['opponent_id'], unique=False)
    op.create_index(op.f('ix_game_sessions_user_id'), 'game_sessions', ['user_id'], unique=False)
    op.create_table('gameplans',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False, comment='Gameplan name'),
    sa.Column('opponent_id', sa.String(length=36), nullable=True),
    sa.Column('plays', sa.JSON(), nullable=True, comment='Ordered list of play calls'),
    sa.Column('kill_sheet', sa.JSON(), nullable=True, comment='Opponent-specific exploit sheet'),
    sa.Column('meta_snapshot', sa.Text(), nullable=True, comment='Current meta context when plan was created'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='When this plan becomes stale'),
    sa.Column('is_archived', sa.Boolean(), nullable=False, comment='Soft-delete flag'),
    sa.Column('share_token', sa.String(length=24), nullable=True, comment='Public share token'),
    sa.Column('share_expiry', sa.DateTime(), nullable=True, comment='When the share link expires'),
    sa.Column('share_views', sa.Integer(), nullable=False, comment='Number of times the share link was viewed'),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['opponent_id'], ['opponents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_token')
    )
    op.create_index(op.f('ix_gameplans_opponent_id'), 'gameplans', ['opponent_id'], unique=False)
    op.create_index(op.f('ix_gameplans_user_id'), 'gameplans', ['user_id'], unique=False)
    op.create_table('identity_profiles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('offensive_identity', sa.String(length=100), nullable=True),
    sa.Column('defensive_philosophy', sa.String(length=100), nullable=True),
    sa.Column('risk_tolerance', sa.Integer(), nullable=True),
    sa.Column('pace_preference', sa.String(length=50), nullable=True),
    sa.Column('comfort_zones', sa.JSON(), nullable=True),
    sa.Column('agent_directness', sa.String(length=50), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_identity_profiles_user_id'), 'identity_profiles', ['user_id'], unique=False)
    op.create_table('impact_rankings',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False, comment='Game title'),
    sa.Column('weakness_id', sa.String(length=100), nullable=True, comment='Canonical weakness identifier'),
    sa.Column('description', sa.Text(), nullable=False, comment='Human-readable weakness description'),
    sa.Column('win_rate_damage', sa.Float(), nullable=False, comment='Estimated win-rate cost of this weakness'),
    sa.Column('fix_priority', sa.Integer(), nullable=False, comment='Lower = fix first'),
    sa.Column('expected_lift', sa.Float(), nullable=False, comment='Expected win-rate improvement if fixed'),
    sa.Column('time_to_master', sa.String(length=50), nullable=True, comment="Estimated time to resolve e.g. '2 weeks'"),
    sa.Column('status', sa.Enum('ACTIVE', 'RESOLVED', 'DEFERRED', name='impact_status', native_enum=False), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_impact_rankings_status'), 'impact_rankings', ['status'], unique=False)
    op.create_index(op.f('ix_impact_rankings_user_id'), 'impact_rankings', ['user_id'], unique=False)
    op.create_table('integrity_modes',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('environment', sa.Enum('OFFLINE_LAB', 'RANKED', 'TOURNAMENT', 'BROADCAST', name='game_environment', native_enum=False), nullable=False),
    sa.Column('restricted_features', sa.JSON(), nullable=True, comment='Features disabled in current environment'),
    sa.Column('anti_cheat_status', sa.Enum('COMPLIANT', 'WARNING', 'RESTRICTED', name='anti_cheat_status', native_enum=False), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integrity_modes_user_id'), 'integrity_modes', ['user_id'], unique=True)
    op.create_table('madden_plays',
    sa.Column('scheme_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('formation', sa.String(length=100), nullable=False),
    sa.Column('play_type', sa.String(length=50), nullable=False, comment='e.g. pass, run, RPO, screen'),
    sa.Column('success_rate', sa.Float(), nullable=False),
    sa.Column('situation_tags', sa.JSON(), nullable=True, comment='Situational tags: down, distance, field_zone'),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['scheme_id'], ['madden_schemes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_madden_plays_formation'), 'madden_plays', ['formation'], unique=False)
    op.create_index(op.f('ix_madden_plays_scheme_id'), 'madden_plays', ['scheme_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('action_url', sa.String(length=500), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('player_profiles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False, comment='Game title this profile is for'),
    sa.Column('tendencies', sa.JSON(), nullable=True, comment='Behavioral tendencies extracted from gameplay'),
    sa.Column('execution_ceiling', sa.JSON(), nullable=True, comment='Max skill metrics across categories'),
    sa.Column('panic_patterns', sa.JSON(), nullable=True, comment='Patterns observed under pressure'),
    sa.Column('identity', sa.JSON(), nullable=True, comment='Core identity: risk_tolerance, aggression, pace, style'),
    sa.Column('input_type', sa.Enum('CONTROLLER', 'KBM', 'FIGHTSTICK', name='input_type', native_enum=False), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_profiles_user_id'), 'player_profiles', ['user_id'], unique=True)
    op.create_table('player_twins',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title_id', sa.String(length=50), nullable=False),
    sa.Column('tendencies', sa.JSON(), nullable=True),
    sa.Column('execution_ceiling', sa.JSON(), nullable=True),
    sa.Column('panic_patterns', sa.JSON(), nullable=True),
    sa.Column('coverage_accuracy', sa.JSON(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_twins_user_id'), 'player_twins', ['user_id'], unique=False)
    op.create_table('push_subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('subscription_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referrals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('referrer_id', sa.String(length=36), nullable=False),
    sa.Column('referred_id', sa.String(length=36), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('converted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['referred_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('secret_weapons',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('title_id', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('sub_category', sa.String(length=64), nullable=True),
    sa.Column('formation', sa.String(length=120), nullable=True),
    sa.Column('play_name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('instructions', sa.JSON(), nullable=False),
    sa.Column('setup_steps', sa.JSON(), nullable=False),
    sa.Column('when_to_use', sa.Text(), nullable=False),
    sa.Column('trigger_conditions', sa.JSON(), nullable=False),
    sa.Column('difficulty', sa.String(length=16), nullable=False),
    sa.Column('title_specific_data', sa.JSON(), nullable=False),
    sa.Column('success_rate', sa.Float(), nullable=False),
    sa.Column('times_used', sa.Integer(), nullable=False),
    sa.Column('patch_version', sa.String(length=32), nullable=True),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('community_rating', sa.Float(), nullable=False),
    sa.Column('community_votes', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_secret_weapons_category'), 'secret_weapons', ['category'], unique=False)
    op.create_index(op.f('ix_secret_weapons_side'), 'secret_weapons', ['side'], unique=False)
    op.create_index(op.f('ix_secret_weapons_title_id'), 'secret_weapons', ['title_id'], unique=False)
    op.create_index(op.f('ix_secret_weapons_user_id'), 'secret_weapons', ['user_id'], unique=False)
    op.create_table('support_tickets',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False, comment='billing, bug, account, feature, feedback, other'),
    sa.Column('priority', sa.String(length=20), nullable=False, comment='low, normal, high'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='open, in_progress, resolved'),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vault_entries',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title_id', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vault_entries_user_id'), 'vault_entries', ['user_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('agent_source', sa.String(length=100), nullable=False, comment='Which AI agent generated this'),
    sa.Column('recommendation_type', sa.String(length=100), nullable=False, comment='Category of recommendation'),
    sa.Column('content', sa.JSON(), nullable=False, comment='Full recommendation payload'),
    sa.Column('confidence_score', sa.Float(), nullable=False, comment='Agent confidence 0.0-1.0'),
    sa.Column('impact_score', sa.Float(), nullable=True, comment='Measured impact after follow-through'),
    sa.Column('was_followed', sa.Boolean(), nullable=True, comment='Did the player follow this?'),
    sa.Column('outcome_correct', sa.Boolean(), nullable=True, comment='Was the prediction correct?'),
    sa.Column('feedback_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the player submitted follow/dismiss feedback'),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_session_id'), 'recommendations', ['session_id'], unique=False)
    op.create_index(op.f('ix_recommendations_user_id'), 'recommendations', ['user_id'], unique=False)
    op.create_table('user_arsenal',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('weapon_id', sa.String(length=36), nullable=False),
    sa.Column('title_id', sa.String(length=32), nullable=False),
    sa.Column('saved_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['weapon_id'], ['secret_weapons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'weapon_id', name='uq_user_arsenal_user_weapon')
    )
    op.create_index(op.f('ix_user_arsenal_title_id'), 'user_arsenal', ['title_id'], unique=False)
    op.create_index(op.f('ix_user_arsenal_user_id'), 'user_arsenal', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_arsenal_weapon_id'), 'user_arsenal', ['weapon_id'], unique=False)
    op.create_table('weapon_usage_log',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('weapon_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('title_id', sa.String(length=32), nullable=False),
    sa.Column('game_state', sa.JSON(), nullable=True),
    sa.Column('deployed', sa.Boolean(), nullable=False),
    sa.Column('worked', sa.Boolean(), nullable=True),
    sa.Column('opponent_adjusted', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['weapon_id'], ['secret_weapons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weapon_usage_log_title_id'), 'weapon_usage_log', ['title_id'], unique=False)
    op.create_index(op.f('ix_weapon_usage_log_user_id'), 'weapon_usage_log', ['user_id'], unique=False)
    op.create_index(op.f('ix_weapon_usage_log_weapon_id'), 'weapon_usage_log', ['weapon_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weapon_usage_log_weapon_id'), table_name='weapon_usage_log')
    op.drop_index(op.f('ix_weapon_usage_log_user_id'), table_name='weapon_usage_log')
    op.drop_index(op.f('ix_weapon_usage_log_title_id'), table_name='weapon_usage_log')
    op.drop_table('weapon_usage_log')
    op.drop_index(op.f('ix_user_arsenal_weapon_id'), table_name='user_arsenal')
    op.drop_index(op.f('ix_user_arsenal_user_id'), table_name='user_arsenal')
    op.drop_index(op.f('ix_user_arsenal_title_id'), table_name='user_arsenal')
    op.drop_table('user_arsenal')
    op.drop_index(op.f('ix_recommendations_user_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_session_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_vault_entries_user_id'), table_name='vault_entries')
    op.drop_table('vault_entries')
    op.drop_table('support_tickets')
    op.drop_index(op.f('ix_secret_weapons_user_id'), table_name='secret_weapons')
    op.drop_index(op.f('ix_secret_weapons_title_id'), table_name='secret_weapons')
    op.drop_index(op.f('ix_secret_weapons_side'), table_name='secret_weapons')
    op.drop_index(op.f('ix_secret_weapons_category'), table_name='secret_weapons')
    op.drop_table('secret_weapons')
    op.drop_table('referrals')
    op.drop_table('push_subscriptions')
    op.drop_index(op.f('ix_player_twins_user_id'), table_name='player_twins')
    op.drop_table('player_twins')
    op.drop_index(op.f('ix_player_profiles_user_id'), table_name='player_profiles')
    op.drop_table('player_profiles')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_madden_plays_scheme_id'), table_name='madden_plays')
    op.drop_index(op.f('ix_madden_plays_formation'), table_name='madden_plays')
    op.drop_table('madden_plays')
    op.drop_index(op.f('ix_integrity_modes_user_id'), table_name='integrity_modes')
    op.drop_table('integrity_modes')
    op.drop_index(op.f('ix_impact_rankings_user_id'), table_name='impact_rankings')
    op.drop_index(op.f('ix_impact_rankings_status'), table_name='impact_rankings')
    op.drop_table('impact_rankings')
    op.drop_index(op.f('ix_identity_profiles_user_id'), table_name='identity_profiles')
    op.drop_table('identity_profiles')
    op.drop_index(op.f('ix_gameplans_user_id'), table_name='gameplans')
    op.drop_index(op.f('ix_gameplans_opponent_id'), table_name='gameplans')
    op.drop_table('gameplans')
    op.drop_index(op.f('ix_game_sessions_user_id'), table_name='game_sessions')
    op.drop_index(op.f('ix_game_sessions_opponent_id'), table_name='game_sessions')
    op.drop_table('game_sessions')
    op.drop_index(op.f('ix_drills_user_id'), table_name='drills')
    op.drop_table('drills')
    op.drop_index(op.f('ix_defensive_priorities_user_id'), table_name='defensive_priorities')
    op.drop_index(op.f('ix_defensive_priorities_title_id'), table_name='defensive_priorities')
    op.drop_table('defensive_priorities')
    op.drop_index(op.f('ix_defensive_gameplans_user_id'), table_name='defensive_gameplans')
    op.drop_index(op.f('ix_defensive_gameplans_title_id'), table_name='defensive_gameplans')
    op.drop_table('defensive_gameplans')
    op.drop_index(op.f('ix_daily_forge_streaks_user_id'), table_name='daily_forge_streaks')
    op.drop_table('daily_forge_streaks')
    op.drop_index(op.f('ix_daily_forge_completions_user_id'), table_name='daily_forge_completions')
    op.drop_index(op.f('ix_daily_forge_completions_date'), table_name='daily_forge_completions')
    op.drop_table('daily_forge_completions')
    op.drop_index(op.f('ix_cfb_recruiting_targets_user_id'), table_name='cfb_recruiting_targets')
    op.drop_index(op.f('ix_cfb_recruiting_targets_position'), table_name='cfb_recruiting_targets')
    op.drop_index(op.f('ix_cfb_recruiting_targets_pipeline_stage'), table_name='cfb_recruiting_targets')
    op.drop_table('cfb_recruiting_targets')
    op.drop_index(op.f('ix_cfb_plays_scheme_id'), table_name='cfb_plays')
    op.drop_index(op.f('ix_cfb_plays_formation'), table_name='cfb_plays')
    op.drop_table('cfb_plays')
    op.drop_table('certifications')
    op.drop_table('api_usage')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_opponents_gamertag'), table_name='opponents')
    op.drop_index(op.f('ix_opponents_external_id'), table_name='opponents')
    op.drop_table('opponents')
    op.drop_index(op.f('ix_madden_schemes_name'), table_name='madden_schemes')
    op.drop_table('madden_schemes')
    op.drop_index(op.f('ix_cfb_schemes_name'), table_name='cfb_schemes')
    op.drop_table('cfb_schemes')
    op.drop_index(op.f('ix_animaforge_jobs_user_id'), table_name='animaforge_jobs')
    op.drop_index(op.f('ix_animaforge_jobs_type'), table_name='animaforge_jobs')
    op.drop_index(op.f('ix_animaforge_jobs_title_id'), table_name='animaforge_jobs')
    op.drop_index(op.f('ix_animaforge_jobs_status'), table_name='animaforge_jobs')
    op.drop_index(op.f('ix_animaforge_jobs_source_id'), table_name='animaforge_jobs')
    op.drop_index(op.f('ix_animaforge_jobs_job_id'), table_name='animaforge_jobs')
    op.drop_table('animaforge_jobs')
    op.drop_index(op.f('ix_agent_performances_agent_name'), table_name='agent_performances')
    op.drop_table('agent_performances')
    # ### end Alembic commands ###
