"""EA FC 26 Pydantic schemas for SquadForge, TacticsForge, SkillForge, SetPieceForge."""

from app.schemas.eafc26.squad import (
    BudgetOptimization,
    CardValue,
    CardValueTrend,
    ChemistryLink,
    ChemistryReport,
    ChemistryType,
    EAFCPlaystyle,
    EAFCPlaystyleProfile,
    EAFCTwinProfile,
    PlayerCard,
    RageSubDetection,
    SquadAnalysis,
    SquadSlot,
    TiltIndicator,
)
from app.schemas.eafc26.tactics import (
    CornerRoutine,
    CounterTactic,
    CustomInstruction,
    FormationMeta,
    FreeKickSetup,
    InputTimingResult,
    PenaltyAnalysis,
    SetPieceReport,
    SkillChain,
    SkillMoveAnalysis,
    TacticalReport,
)

__all__ = [
    "BudgetOptimization",
    "CardValue",
    "CardValueTrend",
    "ChemistryLink",
    "ChemistryReport",
    "ChemistryType",
    "CornerRoutine",
    "CounterTactic",
    "CustomInstruction",
    "EAFCPlaystyle",
    "EAFCPlaystyleProfile",
    "EAFCTwinProfile",
    "FormationMeta",
    "FreeKickSetup",
    "InputTimingResult",
    "PenaltyAnalysis",
    "PlayerCard",
    "RageSubDetection",
    "SetPieceReport",
    "SkillChain",
    "SkillMoveAnalysis",
    "SquadAnalysis",
    "SquadSlot",
    "TacticalReport",
    "TiltIndicator",
]
