"""UFC 5 Pydantic schemas for combat intelligence and career management."""

from app.schemas.ufc5.combat import (
    BodyRegion,
    CutSeverity,
    DamageEntry,
    DamageState,
    FighterArchetype,
    FighterBuild,
    FighterStylePath,
    FinishProtocol,
    GrapplePosition,
    GrappleTransition,
    PerkRanking,
    RoundPlan,
    RoundScore,
    StaminaEconomy,
    StaminaPhase,
    StrikeType,
    StyleMatchup,
    SubmissionChain,
    VulnerabilityWindow,
)

__all__ = [
    "BodyRegion",
    "CutSeverity",
    "DamageEntry",
    "DamageState",
    "FighterArchetype",
    "FighterBuild",
    "FighterStylePath",
    "FinishProtocol",
    "GrapplePosition",
    "GrappleTransition",
    "PerkRanking",
    "RoundPlan",
    "RoundScore",
    "StaminaEconomy",
    "StaminaPhase",
    "StrikeType",
    "StyleMatchup",
    "SubmissionChain",
    "VulnerabilityWindow",
]
